% for axial symmetry around z axis only
function energy = exc_final(rho)
    global Cx
    global a
    global b1
    global b2
    global box_size
    energy = integral2(...
        @(x,z)...
        (...
            -Cx * rho(x, 0, z).^(1/3) +...
            a * log(1 + b1 * rho(x, 0, z).^(1/3) + b2 * rho(x, 0, z).^(2/3))...
        )...
        .* rho(x, 0, z) * 2 * pi .* x,...
        0, box_size, -box_size, box_size ...
    );
end