function vxc = lda_chachiyo_vxc(rho, bra, ket)
    global Cx
    global a
    global b1
    global b2
    global box_size
    vxc = integral3(...
        @(x,y,z)...
        (...
            1/3 * ...
            (...
                -4 * Cx + ...
                ( a * ( b1 + 2 * b2 * rho(x,y,z).^(1/3) ) )...
                ./...
                ( 1 + b1 * rho(x,y,z).^(1/3) + b2 * rho(x,y,z).^(2/3) )...
            )...
            .* rho(x,y,z).^(1/3)...
            + a * log( 1 + b1 * rho(x,y,z).^(1/3) + b2 * rho(x,y,z).^(2/3) )...
        )...
        .* bra(x,y,z) .* ket(x,y,z),...
        -box_size, box_size, -box_size, box_size, -box_size, box_size ...
    );
end