% for GTO 1s only
function S = overlap_int(basis_alphas, basis_centers)
    S = zeros(length(basis_alphas), length(basis_alphas));
    for i = 1:length(basis_alphas)
        for j = 1:length(basis_alphas)
            a = basis_alphas{i};
            b = basis_alphas{j};
            S(i,j) = ...
                (2 * a / pi)^(3/4)...
                * (2 * b / pi)^(3/4)...
                * (pi / (a + b))^(3/2)...
                * exp(...
                    -(a * b)/(a + b)...
                    * norm(basis_centers{i} - basis_centers{j})^2 ...
                );
        end
    end
end