% for GTO 1s only
function V = two_electron_int(basis_alphas, basis_centers)
    V = zeros(length(basis_alphas), length(basis_alphas),...
        length(basis_alphas), length(basis_alphas));
    for i = 1:length(basis_alphas)
        for j = 1:length(basis_alphas)
            for k = 1:length(basis_alphas)
                for l = 1:length(basis_alphas)
                    a = basis_alphas{i};
                    ra = basis_centers{i};
                    b = basis_alphas{j};
                    rb = basis_centers{j};
                    rp = (a * ra + b * rb) / (a + b);
                    c = basis_alphas{k};
                    rc = basis_centers{k};
                    d = basis_alphas{l};
                    rd = basis_centers{l};
                    rq = (c * rc + d * rd) / (c + d);
                    
                    V(i,j,k,l) = ...
                    (2 * a / pi)^(3/4) *...
                    (2 * b / pi)^(3/4) *...
                    (2 * c / pi)^(3/4) *...
                    (2 * d / pi)^(3/4) *...
                    2 * pi^(5/2) /...
                    ((a + b) * (c + d) * sqrt(a + b + c + d)) * ...
                    exp(...
                        -a * b / (a + b) * norm(ra - rb)^2 ...
                        -c * d / (c + d) * norm(rc - rd)^2 ...
                    ) * ...
                    incomplete_gamma(...
                        norm(rp - rq)^2 * (a + b) * (c + d) / ...
                        (a + b + c + d)...
                    );
                end
            end
        end
    end
end